Warn about #264 in the README

diff --git a/plugins/python-build/bin/python-build b/plugins/python-build/bin/python-build
--- a/plugins/python-build/bin/python-build
+++ b/plugins/python-build/bin/python-build
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-PYTHON_BUILD_VERSION="20141028"
+PYTHON_BUILD_VERSION="20140524"
 
 set -E
 exec 3<&2 # preserve original stderr at fd 3
@@ -71,41 +71,17 @@ colorize() {
   fi
 }
 
-os_information() {
-  if type -p lsb_release >/dev/null; then
-    lsb_release -sir | xargs echo
-  elif type -p sw_vers >/dev/null; then
-    echo "OS X $(sw_vers -productVersion)"
-  elif [ -r /etc/os-release ]; then
-    source /etc/os-release
-    echo "$NAME" $VERSION_ID
-  else
-    local os="$(cat /etc/{centos,redhat,fedora,system}-release /etc/debian_version 2>/dev/null | head -1)"
-    echo "${os:-$(uname -sr)}"
-  fi
-}
-
-#  9.1  -> 901
-# 10.9  -> 1009
-# 10.10 -> 1010
-osx_version() {
-  local -a ver
-  IFS=. ver=( `sw_vers -productVersion` )
-  echo $(( ${ver[0]}*100 + ${ver[1]} ))
-}
-
 build_failed() {
   { echo
-    colorize 1 "BUILD FAILED"
-    echo " ($(os_information) using $(version))"
+    echo "BUILD FAILED"
     echo
 
     if ! rmdir "${BUILD_PATH}" 2>/dev/null; then
       echo "Inspect or clean up the working tree at ${BUILD_PATH}"
 
       if file_is_not_empty "$LOG_PATH"; then
-        colorize 33 "Results logged to ${LOG_PATH}"
-        printf "\n\n"
+        echo "Results logged to ${LOG_PATH}"
+        echo
         echo "Last 10 log lines:"
         tail -n 10 "$LOG_PATH"
       fi
@@ -127,16 +103,13 @@ file_is_not_empty() {
 }
 
 num_cpu_cores() {
-  local num
-  case "$(uname -s)" in
-  Darwin | *BSD )
+  local num=""
+  if [ "Darwin" = "$(uname -s)" ]; then
     num="$(sysctl -n hw.ncpu 2>/dev/null || true)"
-    ;;
-  * )
-    num="$(grep ^processor /proc/cpuinfo 2>/dev/null | wc -l | xargs)"
-    num="${num#0}"
-    ;;
-  esac
+  elif [ -r /proc/cpuinfo ]; then
+    num="$(grep ^processor /proc/cpuinfo | wc -l)"
+    [ "$num" -gt 0 ] || num=""
+  fi
   echo "${num:-2}"
 }
 
@@ -217,8 +190,7 @@ compute_sha2() {
     output="$(shasum -a 256 -b)" || return 1
     echo "${output% *}"
   elif type openssl &>/dev/null; then
-    local openssl="$(command -v "$(brew --prefix openssl 2>/dev/null)"/bin/openssl openssl | head -1)"
-    output="$("$openssl" dgst -sha256 2>/dev/null)" || return 1
+    output="$(openssl dgst -sha256)" || return 1
     echo "${output##* }"
   elif type sha256sum &>/dev/null; then
     output="$(sha256sum --quiet)" || return 1
@@ -323,7 +295,7 @@ fetch_tarball() {
     fi
   fi
 
-  local tar_args="xzf"
+  local tar_args="xzvf"
   local package_filename="${package_name}.tar.gz"
 
   if [ "$package_url" != "${package_url%tgz}" ]; then
@@ -635,9 +607,6 @@ build_package_standard() {
   ( if [ "${CFLAGS+defined}" ] || [ "${!PACKAGE_CFLAGS+defined}" ]; then
       export CFLAGS="$CFLAGS ${!PACKAGE_CFLAGS}"
     fi
-    if [ -z "$CC" ] && [ "$(uname -s)" = "Darwin" ] && [ "$(osx_version)" -ge 1010 ]; then
-      export CC=clang
-    fi
     ${!PACKAGE_CONFIGURE:-./configure} --prefix="${!PACKAGE_PREFIX_PATH:-$PREFIX_PATH}" \
                                        --libdir="${!PACKAGE_PREFIX_PATH:-$PREFIX_PATH}/lib" \
                                        $CONFIGURE_OPTS ${!PACKAGE_CONFIGURE_OPTS} "${!PACKAGE_CONFIGURE_OPTS_ARRAY}"
@@ -690,12 +659,8 @@ build_package_ree_installer() {
 build_package_rbx() {
   local package_name="$1"
 
-  { [ ! -e "Gemfile" ] || bundle --path=vendor/bundle
-    if [ -n "$RUBY_BUILD_CACHE_PATH" ]; then
-      mkdir -p vendor
-      ln -s "$RUBY_BUILD_CACHE_PATH" vendor/prebuilt
-    fi
-    RUBYOPT="-rubygems $RUBYOPT" ./configure --prefix="$PREFIX_PATH" $RUBY_CONFIGURE_OPTS "${RUBY_CONFIGURE_OPTS_ARRAY[@]}"
+  { bundle --path=vendor/bundle
+    RUBYOPT="-rubygems $RUBYOPT" ./configure --prefix="$PREFIX_PATH" $RUBY_CONFIGURE_OPTS
     rake install
     fix_rbx_gem_binstubs "$PREFIX_PATH"
     fix_rbx_irb "$PREFIX_PATH"
@@ -944,7 +909,7 @@ fix_rbx_gem_binstubs() {
   local bindir="${prefix}/bin"
   local file binstub
   # Symlink Rubinius' `gems/bin/` into `bin/`
-  if [ -d "$gemdir" ] && [ ! -L "$gemdir" ]; then
+  if [ -d "$gemdir" ]; then
     for file in "$gemdir"/*; do
       binstub="${bindir}/${file##*/}"
       rm -f "$binstub"
@@ -1020,9 +985,6 @@ require_gcc() {
   fi
 
   export CC="$gcc"
-  if [ "$(uname -s)" = "Darwin" ] && [ "$(osx_version)" -ge 1010 ]; then
-    export MACOSX_DEPLOYMENT_TARGET=10.9
-  fi
 }
 
 locate_gcc() {
@@ -1061,7 +1023,7 @@ verify_gcc() {
     return 1
   fi
 
-  local version="$("$gcc" --version 2>/dev/null || true)"
+  local version="$("$gcc" --version || true)"
   if [ -z "$version" ]; then
     return 1
   fi
@@ -1073,13 +1035,38 @@ verify_gcc() {
   echo "$gcc"
 }
 
-require_llvm() {
-  local llvm_version="$1"
-  if [ "$(uname -s)" = "Darwin" ] && [ "$(osx_version)" -ge 1010 ]; then
-    if [[ "$PYTHON_CONFIGURE_OPTS" != *--llvm-* ]]; then
-      package_option python configure --prebuilt-name="llvm-3.2-x86_64-apple-darwin13.tar.bz2"
-    fi
+require_cc() {
+  local cc="$(command -v "$CC" || command -v "cc" || true)"
+
+  if [ -z "$cc" ]; then
+    { echo
+      colorize 1 "ERROR"
+      echo ": This package must be compiled with cc, but python-build couldn't"
+      echo "find a suitable \`cc\` executable on your system. Please install cc"
+      echo "and try again."
+      echo
+    } >&3
+    return 1
   fi
+
+  export CC
+}
+
+require_clang() {
+  local clang="$(command -v "$CC" || command -v "clang" || true)"
+
+  if [ -z "$clang" ]; then
+    { echo
+      colorize 1 "ERROR"
+      echo ": This package must be compiled with clang, but python-build couldn't"
+      echo "find a suitable \`clang\` executable on your system. Please install clang"
+      echo "and try again."
+      echo
+    } >&3
+    return 1
+  fi
+ 
+  export CC="$clang"
 }
 
 require_java() {
@@ -1100,7 +1087,6 @@ require_java() {
 }
 
 needs_yaml() {
-  [[ "$RUBY_CONFIGURE_OPTS" != *--with-libyaml-dir=* ]] &&
   ! use_homebrew_yaml
 }
 
@@ -1150,8 +1136,7 @@ use_homebrew_readline() {
 
 has_broken_mac_openssl() {
   [ "$(uname -s)" = "Darwin" ] &&
-  [[ "$(/usr/bin/openssl version 2>/dev/null || true)" = "OpenSSL 0.9.8"?* ]] &&
-  [[ "$RUBY_CONFIGURE_OPTS" != *--with-openssl-dir=* ]] &&
+  [[ "$(openssl version 2>/dev/null || true)" = "OpenSSL 0.9.8"?* ]] &&
   ! use_homebrew_openssl
 }
 
@@ -1181,7 +1166,7 @@ build_package_mac_openssl() {
   OPENSSL_CONFIGURE="${OPENSSL_CONFIGURE:-./config}"
 
   # Compile a shared lib with zlib dynamically linked, no kerberos.
-  package_option openssl configure --openssldir="$OPENSSLDIR" zlib-dynamic no-ssl2 no-ssl3 no-krb5 shared
+  package_option openssl configure --openssldir="$OPENSSLDIR" zlib-dynamic no-krb5 shared
 
   # Default MAKE_OPTS are -j 2 which can confuse the build. Thankfully, make
   # gives precedence to the last -j option, so we can override that.
@@ -1200,11 +1185,7 @@ build_package_verify_openssl() {
   "$RUBY_BIN" -e 'begin
     require "openssl"
   rescue LoadError
-    $stderr.puts "The Ruby openssl extension was not compiled. Missing the OpenSSL lib?"
-    $stderr.puts "Configure options used:"
-    require "rbconfig"; require "shellwords"
-    RbConfig::CONFIG.fetch("configure_args").shellsplit.each { |arg| $stderr.puts "  #{arg}" }
-    exit 1
+    abort "The Ruby openssl extension was not compiled. Missing the OpenSSL lib?"
   end' >&4 2>&1
 }
 
@@ -1468,13 +1449,7 @@ build_package_ensurepip() {
 }
 
 version() {
-  local git_revision
-  # Read the revision from git if the remote points to "python-build" repository
-  if GIT_DIR="$PYTHON_BUILD_INSTALL_PREFIX/../../.git" git remote -v 2>/dev/null | grep -q /pyenv; then
-    git_revision="$(GIT_DIR="$PYTHON_BUILD_INSTALL_PREFIX/../../.git" git describe --tags HEAD 2>/dev/null || true)"
-    git_revision="${git_revision#v}"
-  fi
-  echo "python-build ${git_revision:-$PYTHON_BUILD_VERSION}"
+  echo "python-build ${PYTHON_BUILD_VERSION}"
 }
 
 usage() {
@@ -1489,28 +1464,19 @@ usage() {
 }
 
 list_definitions() {
-  { for DEFINITION_DIR in "${PYTHON_BUILD_DEFINITIONS[@]}"; do
-      [ -d "$DEFINITION_DIR" ] && find "$DEFINITION_DIR" -maxdepth 1 -type f -print0 | xargs -0 -n 1 basename 2>/dev/null
+  { for definition in "${PYTHON_BUILD_ROOT}/share/python-build/"*; do
+      [ -f "${definition}" ] && echo "${definition##*/}"
     done
-  } | sort_versions | uniq
+  } | sort
 }
 
-sort_versions() {
-  sed 'h; s/[+-]/./g; s/.p\([[:digit:]]\)/.z\1/; s/$/.z/; G; s/\n/ /' | \
-    LC_ALL=C sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n | awk '{print $2}'
-}
 
 
 unset VERBOSE
 unset KEEP_BUILD_PATH
 unset HAS_PATCH
+PYTHON_BUILD_ROOT="$(abs_dirname "$0")/.."
 unset DEBUG
-
-PYTHON_BUILD_INSTALL_PREFIX="$(abs_dirname "$0")/.."
-
-OLDIFS="$IFS"
-IFS=: PYTHON_BUILD_DEFINITIONS=($PYTHON_BUILD_DEFINITIONS ${PYTHON_BUILD_ROOT:-$PYTHON_BUILD_INSTALL_PREFIX}/share/python-build)
-IFS="$OLDIFS"
 
 parse_options "$@"
 
@@ -1555,14 +1521,10 @@ DEFINITION_PATH="${ARGUMENTS[0]}"
 if [ -z "$DEFINITION_PATH" ]; then
   usage
 elif [ ! -f "$DEFINITION_PATH" ]; then
-  for DEFINITION_DIR in "${PYTHON_BUILD_DEFINITIONS[@]}"; do
-    if [ -f "${DEFINITION_DIR}/${DEFINITION_PATH}" ]; then
-      DEFINITION_PATH="${DEFINITION_DIR}/${DEFINITION_PATH}"
-      break
-    fi
-  done
-
-  if [ ! -f "$DEFINITION_PATH" ]; then
+  BUILTIN_DEFINITION_PATH="${PYTHON_BUILD_ROOT}/share/python-build/${DEFINITION_PATH}"
+  if [ -e "$BUILTIN_DEFINITION_PATH" ]; then
+    DEFINITION_PATH="$BUILTIN_DEFINITION_PATH"
+  else
     echo "python-build: definition not found: ${DEFINITION_PATH}" >&2
     exit 2
   fi
@@ -1581,23 +1543,8 @@ else
   TMP="${TMPDIR%/}"
 fi
 
-# Check if TMPDIR is accessible and can hold executables.
-tmp_executable="${TMP}/python-build-test.$$"
-noexec=""
-if mkdir -p "$TMP" && touch "$tmp_executable" 2>/dev/null; then
-  cat > "$tmp_executable" <<-EOF
-	#!${BASH}
-	exit 0
-	EOF
-  chmod +x "$tmp_executable"
-else
+if [ ! -w "$TMP" ] || [ ! -x "$TMP" ]; then
   echo "python-build: TMPDIR=$TMP is set to a non-accessible location" >&2
-  exit 1
-fi
-"$tmp_executable" 2>/dev/null || noexec=1
-rm -f "$tmp_executable"
-if [ -n "$noexec" ]; then
-  echo "python-build: TMPDIR=$TMP cannot hold executables (partition possibly mounted with \`noexec\`)" >&2
   exit 1
 fi
 
@@ -1612,7 +1559,7 @@ fi
 #fi
 
 if [ -z "$MAKE" ]; then
-  if [ "FreeBSD" = "$(uname -s)" ] && [ "$(uname -r | sed 's/[^[:digit:]].*//')" -lt 10 ]; then
+  if [[ "FreeBSD" = "$(uname -s)" ]]; then
     export MAKE="gmake"
   else
     export MAKE="make"
@@ -1646,6 +1593,7 @@ if echo test | compute_md5 >/dev/null; then
   HAS_MD5_SUPPORT=1
 else
   unset HAS_MD5_SUPPORT
+  unset PYTHON_BUILD_MIRROR_URL
 fi
 
 # Add an option to build a debug version of Python (#11)
@@ -1726,6 +1674,10 @@ if [[ "Darwin" == "$(uname -s)" ]]; then
   MACOS_VERSION_ARRAY=(${MACOS_VERSION//\./ })
   if [ "${#MACOS_VERSION_ARRAY[@]}" -ge 2 ]; then
     export MACOSX_DEPLOYMENT_TARGET="${MACOS_VERSION_ARRAY[0]}.${MACOS_VERSION_ARRAY[1]}"
+  else
+    { colorize 1 "WARNING"
+      echo ": Could not detect the product version of OS X for MACOSX_DEPLOYMENT_TARGET. Use default setting."
+    } >&2
   fi
 fi
 
