Just display warning if `.pydistutils.cfg` exists.

diff --git a/plugins/python-build/bin/python-build b/plugins/python-build/bin/python-build
--- a/plugins/python-build/bin/python-build
+++ b/plugins/python-build/bin/python-build
@@ -969,26 +969,29 @@ verify_gcc() {
 }
 
 require_cc() {
-  local cc=("$@")
-  while [ -n "${cc}" ]; do
-    { if [ "${#cc[@]}" -le 1 ]; then
-        "require_${cc}" # display last error
-      else
-        "require_${cc}" 3>/dev/null
-      fi
-    } && return 0
-    cc=("${cc[@]:1}")
-  done
-  return 1
+  local cc="$(command -v "$CC" || command -v "cc" || true)"
+
+  if [ -z "$cc" ]; then
+    { echo
+      colorize 1 "ERROR"
+      echo ": This package must be compiled with cc, but python-build couldn't"
+      echo "find a suitable \`cc\` executable on your system. Please install cc"
+      echo "and try again."
+      echo
+    } >&3
+    return 1
+  fi
+
+  export CC
 }
 
 require_clang() {
   local clang="$(command -v "$CC" || command -v "clang" || true)"
 
   if [ -z "$clang" ]; then
-    local esc=$'\033'
     { echo
-      echo "${esc}[1mERROR${esc}[0m: This package must be compiled with clang, but python-build couldn't"
+      colorize 1 "ERROR"
+      echo ": This package must be compiled with clang, but python-build couldn't"
       echo "find a suitable \`clang\` executable on your system. Please install clang"
       echo "and try again."
       echo
@@ -1003,9 +1006,9 @@ require_java() {
   local java="$(command -v java || true)"
 
   if [ -z "$java" ]; then
-    local esc=$'\033'
     { echo
-      echo "${esc}[1mERROR${esc}[0m: This package must be installed with java, but python-build couldn't"
+      colorize 1 "ERROR"
+      echo ": This package must be installed with java, but python-build couldn't"
       echo "find a suitable \`java\` executable on your system. Please install Java"
       echo "and try again."
       echo
@@ -1464,8 +1467,9 @@ fi
 
 # pydistutils.cfg may corrupt install location of Python libraries (#35, #111)
 if [ -e "$HOME/.pydistutils.cfg" ]; then
-  echo "python-build: Please make sure you remove any previous custom paths from your $HOME/.pydistutils.cfg file." >&2
-  exit 1
+  { colorize 1 "WARNING"
+    echo ": Please make sure you remove any previous custom paths from your $HOME/.pydistutils.cfg file."
+  } >&2
 fi
 
 SEED="$(date "+%Y%m%d%H%M%S").$$"
