Avoid `rbenv-exec` calling out to `rbenv-version-name` twice

diff --git a/libexec/rbenv-init b/libexec/rbenv-init
--- a/libexec/rbenv-init
+++ b/libexec/rbenv-init
@@ -28,7 +28,31 @@ if [ -z "$shell" ]; then
   shell="$(basename "${shell:-$SHELL}")"
 fi
 
-root="${0%/*}/.."
+READLINK=$(type -p greadlink readlink | head -1)
+if [ -z "$READLINK" ]; then
+  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  exit 1
+fi
+
+resolve_link() {
+  $READLINK "$1"
+}
+
+abs_dirname() {
+  local cwd="$(pwd)"
+  local path="$1"
+
+  while [ -n "$path" ]; do
+    cd "${path%/*}"
+    local name="${path##*/}"
+    path="$(resolve_link "$name" || true)"
+  done
+
+  pwd
+  cd "$cwd"
+}
+
+root="$(abs_dirname "$0")/.."
 
 if [ -z "$print" ]; then
   case "$shell" in
